### PR TITLE
Implement scan and scan_each methods for hash, set, and sorted set

### PR DESCRIPTION
**Pull request by ryanshow**
Implement scan_each, hscan, hscan_each, sscan, sscan_each, zscan, and zscan_each, along will test coverage for all added methods.

### CODE REVIEW

**Comment by ryanshow** [comment]
The test failure seems to be due to differences in how the internals of Ruby sets work vs Redis sets, and how the sets are ordered when returned. I'm not sure exactly what the best solution is, other than disabling the offending test.

**Comment by ryanshow** [comment]
Ok, the offending test has been updated so that sscan is monkey patched on all Redis and MockRedis instances within the context of the test to sort the returned members so that the order of the returned members are deterministic as long as sscan returns all of the members in one call.

**Comment by tdooner** [comment]
Thanks @ryanshow! This looks good to me, and I am especially appreciative for the many thoughtful tests you included.

However, I'm a bit out-of-context on this project, since the main maintainer @sds is out this week. Are you okay waiting until next week for this to be merged?

**Comment by ryanshow** [comment]
Yeah, that's perfectly fine.

**Comment by sds** [comment]
Thanks for the pull request, @ryanshow!

Merged in b8f382e. The workaround for dealing with the order of the returned items in the cursor works for me given it's isolated to just those tests.

**Pull request closed without merging**
