### PR TITLE
Implement unlink

### PR DESCRIPTION
**Pull request by ChrisBr**
https://redis.io/commands/UNLINK.

Not sure if you want me to write tests for it or it is enough that ``del`` is already tested?

### CODE REVIEW

**Comment by sds** [comment]
Hey @ChrisBr, happy to merge, but it looks like the tests fail. Can you investigate and fix?

**Comment by ChrisBr** [comment]
> Hey @ChrisBr, happy to merge, but it looks like the tests fail. Can you investigate and fix?

Sorry for the delay, I will have a look!

**Comment by ChrisBr** [comment]
Hoooray 🎉 

Sorry for the delay but finally got it working 😄 Had some issues with Rubocop and supporting the different versions of Ruby and then forgot about the PR at some point ...

**Comment by ChrisBr** [comment]
🎉 Thanks!

**Pull request merged**
