### PR TITLE
Improve performance of operations with an expiration.

### PR DESCRIPTION
**Pull request by kcdragon**
See issue #118

This PR improves the performance of the of operations with expiration. The performance issue is due to the `expire_times` data structure in the `Database` class. The PR improves the performance by inserting the key-time pair in the `expire_times` Array at the correct position instead of inserting it at the end and re-sorting.

These are the results on my machine for the script mentioned in #118 with 10,000 keys.

```
# before
[mdalton@mdalton-MacBook-Pro-7 mock_redis (master)]$ bundle exec ruby performance.rb
setex
25.877892246004194
set
0.16075976501451805
```

```
# after
[mdalton@mdalton-MacBook-Pro-7 mock_redis (master)]$ bundle exec ruby performance.rb
setex
6.0611226839828305
set
0.13644369100802578
```

My first attempt to fix this issue was to change the data structure for `expire_times` from an `Array` to a `Hash`. I thought this would speed things up since most operations on this data structure in the `Database` class would be performed in constant time with a `Hash` but are linear time with an `Array`. However, when I made this change, the time actually increased. I realized that the reason it was a sorted `Array` to begin with was because it is optimized for the `expire_keys` method.

Even though this PR does not prevent the exponential degradation, it does improve it.

Let me know your thoughts.

### CODE REVIEW

**Comment by denisovlev** [comment]
It's a great improvement, thank you! 
I think that the best solution would be to use a priority queue but it will require bigger changes.

**Comment by sds** [comment]
Hey @kcdragon, thanks for this pull request!

This is great, but unfortunately `Array#bsearch_index` is available only in Ruby 2.3+. We'd like to have something that is at least supported by Ruby 2.0+ (though I would accept Ruby 2.1+ as Ruby 2.0 has been [end-of-lifed](https://www.ruby-lang.org/en/news/2016/02/24/support-plan-of-ruby-2-0-0-and-2-1/)).

**Comment by kcdragon** [comment]
@sds Ah, I always forget about needing to support older versions of Ruby. I could write my own implementation of that method but at a certain point the complexity of that outweighs the small benefit of performance.

**Comment by sds** [comment]
I'm going to close this for now as it seems neither of us has time to work on getting this working with Ruby 2.1+

Perhaps we can revisit once 2.1 and 2.2 are EOLed, at which point it makes sense for MockRedis to consider supporting only Ruby 2.3+.

Thanks again! Feel free to open a new pull request with support for Ruby 2.0.

**Pull request closed without merging**
